opt_in_rules: # some rules are only opt-in
  - colon
  - comma
  - control_statement
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - todo
  - toggle_bool
  - unused_private_declaration

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods/
  - Carthage/
  - {{cookiecutter.app_name}}/Resources

file_length:
  warning: 400
  error: 600

line_length:
  warning: 180
  error: 250

type_body_length:
  - 300 # warning
  - 400 # error

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
   - 3
   - 4

nesting:
  type_level: 3 
  statement_level: 7

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 45

identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - vc

function_parameter_count:
 warning: 8
 error: 15
