# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target '{{cookiecutter.app_name}}' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for {{cookiecutter.app_name}}
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  # Internal
  pod 'NStackSDK', '~> 5.0'
  
  # External
  # pod 'Kingfisher', '~> 6.0'
  pod 'CombineCocoa'
  pod 'CombineExt'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end

end

target 'Domain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'DomainTests' do
    inherit! :search_paths
  end

end

target 'Platform' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'RealmSwift'
#  pod 'Realm'

  target 'PlatformTests' do
    inherit! :search_paths
  end

end
